workflows:
  ios_build:
    name: iOS Build (No Code Signing)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/**/*.xcarchive
