// File generated by FlutterFire CLI & Updated for Defa Official Project.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/**
 * ✅ إعدادات Firebase الرسمية لمشروع دِفا (defa-sa-official)
 * تم الربط بمنطقة بلجيكا (europe-west1) لضمان أداء ملكي فائق السرعة.
 */
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ إعدادات الويب الرسمية (Web) - مشروع defa-sa-official
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm9w7I0aflpNy3ReHqkcmaXJ7n2DP0e-I', // يتم تحديثه من Console المشروع الجديد
    appId: '1:168723405772:web:931bea1795469894b29b69',
    messagingSenderId: '168723405772',
    projectId: 'defa-sa-official', // ✅ المعرف الرسمي الجديد
    authDomain: 'defa-sa-official.firebaseapp.com',
    storageBucket: 'defa-sa-official.firebasestorage.app', // ربط مخزن بلجيكا الرسمي
  );

  // ✅ إعدادات الأندرويد الرسمية (Android)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm9w7I0aflpNy3ReHqkcmaXJ7n2DP0e-I',
    appId: '1:168723405772:android:931bea1795469894b29b69',
    messagingSenderId: '168723405772',
    projectId: 'defa-sa-official', // ✅ المعرف الرسمي الجديد
    storageBucket: 'defa-sa-official.firebasestorage.app',
  );

  // ✅ إعدادات الـ iOS الرسمية (iOS)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm9w7I0aflpNy3ReHqkcmaXJ7n2DP0e-I',
    appId: '1:168723405772:ios:931bea1795469894b29b69',
    messagingSenderId: '168723405772',
    projectId: 'defa-sa-official', // ✅ المعرف الرسمي الجديد
    storageBucket: 'defa-sa-official.firebasestorage.app',
    iosBundleId: 'com.defa.sa.official', // ✅ تحديث المعرف لهوية دِفا الرسمية
  );
}